GET http://localhost:3001/hardware/ 
###

POST http://localhost:3001/clientes/clientes


{
    "dni": 44552343,
    "cuit": 23445523439,
    "nombre": "Nombre Cliente",
    "direccion": "Dirección Cliente",
    "telefono": "123456789",
    "correo": "cliente@correo.com"
}
###